name: env
channels:
  - conda-forge
dependencies:
  - affine
  - attrs
  - cftime
  - geojson
  - netCDF4
  - numpy
  - pyparsing
  - pyugrid
  - scipy
  - Shapely
  - tqdm
  - matplotlib
  - python==3.6
  - pip:
    - earthengine-api
    - google-cloud-storage
    - gsutil
    - rasterio
    - datetime
